### PR TITLE
feat: add French translation

### PR DESCRIPTION
**Pull request by christian-nils**

### CODE REVIEW

**Comment by toringer** [comment]
What's the reason for implementing the Unit model selector? If the unit model was needed to use correct registers across models I would agree it would be needed.

**Comment by christian-nils** [comment]
I apologize, my mistake I was implementing the energy consumption feature for #5, but I pushed it on the wrong branch. I will revert this if you are interested in the fr-FR translation.

**Comment by christian-nils** [comment]
I have reverted the wrong commit. Now only the fr-FR.json file should have been added.

**Comment by toringer** [comment]
I have not done translations before, so had to test it first. Seams like the file needs to be named ```fr.json```.

For my curiosity, will you be using the french translation? Are HERU units widely used in France speaking countries?

**Comment by christian-nils** [comment]
Hi,

I have renamed the file now.

From my knowledge no, they are not widely used in French-speaking countries, but I migrated from France to Sweden 10+ years ago now. That is why I have a HERU unit and that I proposed the French translation ;) (not that I use the French interface anyway... But it may be useful for French expats in Scandinavia where HERU units are available).

**Pull request merged**
